watch_stylesheet: true
watch_config: true
debug: false
komorebi:
    start_command: 'komorebic start --whkd'
    stop_command: 'komorebic stop --whkd'
    reload_command: 'komorebic reload-configuration'
bars:
    status-bar:
        enabled: true
        screens: ['*']
        class_name: 'yasb-bar'
        alignment:
            position: 'top'
            center: false
        blur_effect:
            enabled: true
            acrylic: true
            dark_mode: true
            round_corners: true
            border_color: None
        window_flags: # https://github.com/amnweb/yasb/issues/62#issuecomment-2666880888
            always_on_top: true
            windows_app_bar: true
            hide_on_fullscreen: true
        dimensions:
            width: '100%'
            height: 36
        padding:
            top: 8
            left: 8
            bottom: 8
            right: 8
        widgets:
            left: ['active_window']
            center: ['clock']
            right: ['media', 'taskbar', 'volume', 'apps']
widgets:
    media:
        type: 'yasb.media.MediaWidget'
        options:
            label: '{title} - {artist}'
            label_alt: '{title}'
            max_field_size:
                label: 20
                label_alt: 30
            show_thumbnail: true
            controls_only: false
            controls_left: true
            hide_empty: true
            thumbnail_alpha: 100
            thumbnail_padding: 8
            thumbnail_corner_radius: 0 # Set to 0 for square corners
            icons:
                prev_track: "\ue892"
                next_track: "\ue893"
                play: "\ue768"
                pause: "\ue769"
    active_window:
        type: 'yasb.active_window.ActiveWindowWidget'
        options:
            label: '{win[title]}'
            label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
            label_no_window: ''
            label_icon: true
            label_icon_size: 14
            max_length: 56
            max_length_ellipsis: '...'
            monitor_exclusive: true
    clock:
        type: 'yasb.clock.ClockWidget'
        options:
            label: '{%a %d, %b %H:%M}'
            label_alt: '{%A %d %B %Y, %H:%M}'
            timezones: []
    komorebi_workspaces:
        type: 'komorebi.workspaces.WorkspaceWidget'
        options:
            label_offline: 'Komorebi Offline'
            label_workspace_btn: "\udb81\udc3d"
            label_workspace_active_btn: "\udb81\udc3e"
            label_default_name: '{index}'
            label_zero_index: false
            hide_empty_workspaces: false
            hide_if_offline: false
    komorebi_active_layout:
        type: 'komorebi.active_layout.ActiveLayoutWidget'
        options:
            hide_if_offline: true
            label: '{icon}'
            layouts:
                [
                    'bsp',
                    'columns',
                    'rows',
                    'grid',
                    'vertical_stack',
                    'horizontal_stack',
                    'ultrawide_vertical_stack',
                    'right_main_vertical_stack',
                ]
            layout_icons:
                bsp: 'BSP'
                columns: 'COLS'
                rows: 'ROWS'
                grid: 'GRID'
                vertical_stack: 'V-STACK'
                horizontal_stack: 'H-STACK'
                ultrawide_vertical_stack: 'W-STACK'
                right_main_vertical_stack: 'RMV-STACK'
                monocle: 'MONOCLE'
                maximised: 'MAX'
                floating: 'FLOATING'
                paused: 'PAUSED'
            callbacks:
                on_left: 'next_layout'
                on_middle: 'toggle_monocle'
                on_right: 'prev_layout'
    volume:
        type: 'yasb.volume.VolumeWidget'
        options:
            label: '<span>{icon}</span> {level}'
            label_alt: '{volume}'
            volume_icons:
                - "\ueee8" # Icon for muted
                - "\uf026" # Icon for 0-10% volume
                - "\uf027" # Icon for 11-30% volume
                - "\uf027" # Icon for 31-60% volume
                - "\uf028" # Icon for 61-100% volume
            callbacks:
                on_right: 'exec cmd.exe /c start ms-settings:sound'
    apps:
        type: 'yasb.applications.ApplicationsWidget'
        options:
            label: '{data}'
            app_list:
                - { icon: "\ueb51", launch: 'quick_settings' }
                - { icon: "\uf0a2", launch: 'notification_center' }
            container_padding:
                top: 0
                left: 8
                bottom: 0
                right: 8
    taskbar:
        type: 'yasb.taskbar.TaskbarWidget'
        options:
            icon_size: 14
    # glazewm_tiling_direction:
    #     type: 'glazewm.tiling_direction.GlazewmTilingDirectionWidget'
    #     options:
    #         horizontal_label: "\udb81\udce1"
    #         vertical_label: "\udb81\udce2"
    # glazewm_workspaces:
    #     type: 'glazewm.workspaces.GlazewmWorkspacesWidget'
    #     options:
    #         hide_empty_workspaces: true
    #         hide_if_offline: true
    #         enable_scroll_switching: true
    #         app_icons:
    #             enabled_populated: false
    #             enabled_active: false
    #             size: 16
    #             max_icons: 0
    #             hide_label: false
    #             hide_duplicates: false
    #             hide_floating: false
    #         animation: false
